### ISSUE TITLE
raw data

### ISSUE THREAD

**Issue by YangLin916** [chaichontat/janelia2020#2]
Great thanks for sharing the codes!

Could you please share the raw data for analysis as well? I am new in this field, and really want to learn to code by myself.

Great thanks,

Yang

**Comment by chaichontat** [comment]
Hi, sorry for the delay. You could get the data from [Stringer et al. (2021)](https://www.sciencedirect.com/science/article/pii/S0092867421003731) [here](https://janelia.figshare.com/articles/dataset/Recordings_of_20_000_neurons_from_V1_in_response_to_oriented_stimuli/8279387/3). Note that this is not the exact data that we used here.

**Comment by YangLin916** [comment]
> Hi, sorry for the delay. You could get the data from [Stringer et al. (2021)](https://www.sciencedirect.com/science/article/pii/S0092867421003731) [here](https://janelia.figshare.com/articles/dataset/Recordings_of_20_000_neurons_from_V1_in_response_to_oriented_stimuli/8279387/3). Note that this is not the exact data that we used here.

Great thanks!
